# Jekyll configuration
excerpt_separator: <!--more-->
theme: minima
plugins:
  - jekyll-feed

# GitHub page configuration
domain: kumojin.github.io
url: https://kumojin.github.io

# minima configuration
title: Kumojin Blog
description: >-
  Dev tips from the Kumojin team.
github_username:  kumojin
show_excerpts: true
