title: Kumojin Blog
description: >-
  Dev tips from the Kumojin team.
github_username:  kumojin

# Build settings
theme: minima
plugins:
  - jekyll-feed

domain: kumojin.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://kumojin.github.io  # the base hostname and protocol for your site, e.g. http://example.com


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
